/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maquinaexpendedora;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author ceivg
 */
public class Maquina extends javax.swing.JFrame implements ActionListener {

    Integer m1=0;
    Integer m2=0;
    Integer m5=0;
    Integer m10=0;
    Integer b20=0;
    Integer b50=0;
    Integer b100=0;
    Integer b200=0;
    Integer b500=0;
    Integer cc=0;
    Integer c1=0;
    Integer c2=0;
    Integer c5=0;
    Integer c10=0;
    Integer c20=0;
    Integer c50=0;
    Integer c100=0;
    Integer c200=0;
    Integer c500=0;
    Integer credito=0;
    Integer credmaq=0;
    public Maquina() {
        initComponents();
        btnAddcc.setVisible(false);
        btnGd.setVisible(false);
        p1.setIcon(setPressIcon("/monedas/1p.png",p1,5,5));
        p1.setPressedIcon(setPressIcon("/monedas/1p.png",p1,20,20));
        p2.setIcon(setPressIcon("/monedas/2p.png",p2,5,5));
        p2.setPressedIcon(setPressIcon("/monedas/2p.png",p2,20,20));
        p5.setIcon(setPressIcon("/monedas/5.png",p5,5,5));
        p5.setPressedIcon(setPressIcon("/monedas/5.png",p5,20,20));
        p10.setIcon(setPressIcon("/monedas/10.png",p10,5,5));
        p10.setPressedIcon(setPressIcon("/monedas/10.png",p10,20,20));
        p20.setIcon(setIcono("/monedas/20.jpg",p20));
        p20.setPressedIcon(setPressIcon("/monedas/20.jpg",p20,20,20));
        p50.setIcon(setIcono("/monedas/50.png",p50));
        p50.setPressedIcon(setPressIcon("/monedas/50.png",p50,20,20));
        p100.setIcon(setIcono("/monedas/especimen.png",p100));
        p100.setPressedIcon(setPressIcon("/monedas/especimen.png",p100,20,20));
        p200.setIcon(setIcono("/monedas/200.jpg",p200));
        p200.setPressedIcon(setPressIcon("/monedas/200.jpg",p200,20,20));
        p500.setIcon(setIcono("/monedas/500.png",p500));
        p500.setPressedIcon(setPressIcon("/monedas/500.png",p500,20,20));
        btnM1.setIcon(setIcono("/monedas/btnm.png",btnM1));
        btnM1.setPressedIcon(setPressIcon("/monedas/btnm.png",btnM1,10,10));
        btnM2.setIcon(setIcono("/monedas/btnm.png",btnM2));
        btnM2.setPressedIcon(setPressIcon("/monedas/btnm.png",btnM2,10,10));
        btnM3.setIcon(setIcono("/monedas/btnm.png",btnM3));
        btnM3.setPressedIcon(setPressIcon("/monedas/btnm.png",btnM3,10,10));
        btnM4.setIcon(setIcono("/monedas/btnm.png",btnM4));
        btnM4.setPressedIcon(setPressIcon("/monedas/btnm.png",btnM4,10,10));
        btnM5.setIcon(setIcono("/monedas/btnm.png",btnM5));
        btnM5.setPressedIcon(setPressIcon("/monedas/btnm.png",btnM5,10,10));
        btnM6.setIcon(setIcono("/monedas/btnm.png",btnM6));
        btnM6.setPressedIcon(setPressIcon("/monedas/btnm.png",btnM6,10,10));
        btnM7.setIcon(setIcono("/monedas/btnm.png",btnM7));
        btnM7.setPressedIcon(setPressIcon("/monedas/btnm.png",btnM7,10,10));
        btnM8.setIcon(setIcono("/monedas/btnm.png",btnM8));
        btnM8.setPressedIcon(setPressIcon("/monedas/btnm.png",btnM8,10,10));
        btnCambio.setIcon(setPressIcon("/monedas/btnm.png",btnCambio,20,20));
        btnCambio.setPressedIcon(setPressIcon("/monedas/btnm.png",btnCambio,30,30));
        btnM1.addActionListener(this);
        btnM2.addActionListener(this);
        btnM3.addActionListener(this);
        btnM4.addActionListener(this);
        btnM5.addActionListener(this);
        btnM6.addActionListener(this);
        btnM7.addActionListener(this);
        btnM8.addActionListener(this);
        lblPnl.setText("<html>Bienvenido usuario <p>Porvafor elija su producto<html>");
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customPanel1 = new custom.customPanel();
        btnM1 = new javax.swing.JButton();
        btnM2 = new javax.swing.JButton();
        btnM3 = new javax.swing.JButton();
        btnM4 = new javax.swing.JButton();
        btnM5 = new javax.swing.JButton();
        btnM6 = new javax.swing.JButton();
        btnM7 = new javax.swing.JButton();
        btnM8 = new javax.swing.JButton();
        p1 = new javax.swing.JButton();
        p2 = new javax.swing.JButton();
        p500 = new javax.swing.JButton();
        p5 = new javax.swing.JButton();
        p10 = new javax.swing.JButton();
        p20 = new javax.swing.JButton();
        p200 = new javax.swing.JButton();
        p100 = new javax.swing.JButton();
        p50 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblC1p = new javax.swing.JLabel();
        lblC2p = new javax.swing.JLabel();
        lblC5p = new javax.swing.JLabel();
        lblC10p = new javax.swing.JLabel();
        lblC20p = new javax.swing.JLabel();
        lblC50p = new javax.swing.JLabel();
        lblC100p = new javax.swing.JLabel();
        lblC200p = new javax.swing.JLabel();
        lblC500p = new javax.swing.JLabel();
        lblCcc = new javax.swing.JLabel();
        btnMaster = new javax.swing.JToggleButton();
        btnAddcc = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblPnl = new javax.swing.JLabel();
        btnCambio = new javax.swing.JButton();
        btnGd = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnM1.setContentAreaFilled(false);
        btnM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnM1ActionPerformed(evt);
            }
        });

        btnM2.setContentAreaFilled(false);
        btnM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnM2ActionPerformed(evt);
            }
        });

        btnM3.setContentAreaFilled(false);
        btnM3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnM3ActionPerformed(evt);
            }
        });

        btnM4.setContentAreaFilled(false);
        btnM4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnM4ActionPerformed(evt);
            }
        });

        btnM5.setContentAreaFilled(false);
        btnM5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnM5ActionPerformed(evt);
            }
        });

        btnM6.setContentAreaFilled(false);
        btnM6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnM6ActionPerformed(evt);
            }
        });

        btnM7.setContentAreaFilled(false);
        btnM7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnM7ActionPerformed(evt);
            }
        });

        btnM8.setContentAreaFilled(false);
        btnM8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnM8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customPanel1Layout = new javax.swing.GroupLayout(customPanel1);
        customPanel1.setLayout(customPanel1Layout);
        customPanel1Layout.setHorizontalGroup(
            customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customPanel1Layout.createSequentialGroup()
                .addGroup(customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(customPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnM1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnM3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(customPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnM7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnM6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(customPanel1Layout.createSequentialGroup()
                        .addComponent(btnM5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(btnM8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(customPanel1Layout.createSequentialGroup()
                        .addComponent(btnM2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnM4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        customPanel1Layout.setVerticalGroup(
            customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnM4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnM3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnM2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnM1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnM8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnM6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnM5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnM7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p1.setContentAreaFilled(false);
        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });

        p2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p2.setContentAreaFilled(false);
        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });

        p500.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p500.setContentAreaFilled(false);
        p500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p500ActionPerformed(evt);
            }
        });

        p5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p5.setContentAreaFilled(false);
        p5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p5ActionPerformed(evt);
            }
        });

        p10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p10.setContentAreaFilled(false);
        p10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p10ActionPerformed(evt);
            }
        });

        p20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p20.setContentAreaFilled(false);
        p20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p20ActionPerformed(evt);
            }
        });

        p200.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p200.setContentAreaFilled(false);
        p200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p200ActionPerformed(evt);
            }
        });

        p100.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p100.setContentAreaFilled(false);
        p100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p100ActionPerformed(evt);
            }
        });

        p50.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p50.setContentAreaFilled(false);
        p50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p50ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel1.setText("Cuenta interna");

        lblC1p.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        lblC1p.setText("0 Monedas de 1 peso");

        lblC2p.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        lblC2p.setText("0 Monedas de 2 pesos");

        lblC5p.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        lblC5p.setText("0 Monedas de 5 pesos");

        lblC10p.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        lblC10p.setText("0 Monedas de 10 pesos");

        lblC20p.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        lblC20p.setText("0 Billetes de 20 pesos");

        lblC50p.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        lblC50p.setText("0 Billetes de 50 pesos");

        lblC100p.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        lblC100p.setText("0 Billetes de 100 pesos");

        lblC200p.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        lblC200p.setText("0 Billetes de 200 pesos");

        lblC500p.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        lblC500p.setText("0 Billetes de 500 pesos");

        lblCcc.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        lblCcc.setText("0 Botellas de coca");

        btnMaster.setText("Modo maestro");
        btnMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasterActionPerformed(evt);
            }
        });

        btnAddcc.setText("Agregar cocas");
        btnAddcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddccActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblPnl.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        lblPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPnl.setText("Bienvenido Usuario ");
        lblPnl.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblPnl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnCambio.setText("Cambio");
        btnCambio.setToolTipText("");
        btnCambio.setContentAreaFilled(false);
        btnCambio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCambio.setInheritsPopupMenu(true);
        btnCambio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnCambio)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnGd.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnGd.setText("Guardar dinero");
        btnGd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGdActionPerformed(evt);
            }
        });

        jMenu1.setText("Help");

        jMenuItem1.setText("Info");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(customPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnGd))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddcc)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(p500, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMaster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(p200, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(p100, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(p20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(p50, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(166, 166, 166)
                            .addComponent(p10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblC1p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblC2p, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblC5p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblC10p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblC20p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblC50p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblC100p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblC200p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblC500p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblC1p)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblC2p)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblC5p)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblC10p)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblC20p)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblC50p)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblC100p, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblC200p)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(p10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblC500p)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCcc)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(44, 44, 44)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMaster)
                            .addComponent(btnAddcc)))
                    .addComponent(p20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p50, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p100, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p200, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(p500, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGd))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
        m2++;
        lblC2p.setText(m2+" Monedas de 2 pesos");
        if(!(btnGd.isSelected())){
            credito+=2;
            credmaq+=2;
            lblPnl.setText("Credito: $"+credito);
        }else{
            credmaq+=2;
        }
    }//GEN-LAST:event_p2ActionPerformed

    private void p10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p10ActionPerformed
        m10++;
        lblC10p.setText(m10+" Monedas de 10 pesos");
        if(!(btnGd.isSelected())){
            credito+=10;
            credmaq+=10;
            lblPnl.setText("Credito: $"+credito);
        }else{
            credmaq+=10;
        }
    }//GEN-LAST:event_p10ActionPerformed

    private void p200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p200ActionPerformed
        b200++;
        lblC200p.setText(b200+" Billetes de 200 pesos");
        if(!(btnGd.isSelected())){
            credito+=200;
            credmaq+=200;
            lblPnl.setText("Credito: $"+credito);
        }else{
            credmaq+=200;
        }
    }//GEN-LAST:event_p200ActionPerformed

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
        m1++;
        lblC1p.setText(m1+" Monedas de 1 peso");
        if(!(btnGd.isSelected())){
            credito+=1;
            credmaq+=1;
            lblPnl.setText("Credito: $"+credito);
        }else{
            credmaq+=1;
        }
    }//GEN-LAST:event_p1ActionPerformed

    private void btnMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasterActionPerformed
        if(btnMaster.isSelected()){
            btnAddcc.setVisible(true);
            btnGd.setVisible(true);
        }
        else{
            btnAddcc.setVisible(false);
            btnGd.setVisible(false);
        }
    }//GEN-LAST:event_btnMasterActionPerformed

    private void btnAddccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddccActionPerformed
        cc++;
        lblCcc.setText(cc+" Botellas de coca");
    }//GEN-LAST:event_btnAddccActionPerformed

    private void p5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p5ActionPerformed
        m5++;
        lblC5p.setText(m5+" Monedas de 5 pesos");
        if(!(btnGd.isSelected())){
            credito+=5;
            credmaq+=5;
            lblPnl.setText("Credito: $"+credito);
        }else{
            credmaq+=5;
        }
    }//GEN-LAST:event_p5ActionPerformed

    private void p50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p50ActionPerformed
        b50++;
        lblC50p.setText(b50+" Billetes de 50 pesos");
        if(!(btnGd.isSelected())){
            credito+=50;
            credmaq+=50;
            lblPnl.setText("Credito: $"+credito);
        }else{
            credmaq+=50;
        }
    }//GEN-LAST:event_p50ActionPerformed

    private void p20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p20ActionPerformed
        b20++;
        lblC20p.setText(b20+" Billetes de 20 pesos");
        if(!(btnGd.isSelected())){
            credito+=20;
            credmaq+=20;
            lblPnl.setText("Credito: $"+credito);
        }else{
            credmaq+=20;
        }
    }//GEN-LAST:event_p20ActionPerformed

    private void p100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p100ActionPerformed
        b100++;
        lblC100p.setText(b100+" Billetes de 100 pesos");
        if(!(btnGd.isSelected())){
            credito+=100;
            credmaq+=100;
            lblPnl.setText("Credito: $"+credito);
        }else{
            credmaq+=100;
        }
    }//GEN-LAST:event_p100ActionPerformed

    private void p500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p500ActionPerformed
        b500++;
        lblC500p.setText(b500+" Billetes de 500 pesos");
        if(!(btnGd.isSelected())){
            credito+=500;
            credmaq+=500;
            lblPnl.setText("Credito: $"+credito);
        }else{
            credmaq+=500;
        }
    }//GEN-LAST:event_p500ActionPerformed

    private void btnGdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGdActionPerformed

    private void btnM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnM1ActionPerformed

    private void btnM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnM2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnM2ActionPerformed

    private void btnM3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnM3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnM3ActionPerformed

    private void btnM4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnM4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnM4ActionPerformed

    private void btnM5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnM5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnM5ActionPerformed

    private void btnM6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnM6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnM6ActionPerformed

    private void btnM7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnM7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnM7ActionPerformed

    private void btnM8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnM8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnM8ActionPerformed

    private void btnCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambioActionPerformed
        regresarCambiosinCC();
    }//GEN-LAST:event_btnCambioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(this, "<html>Para agregar cocas o dinero a la maquina basta con activar el boton de modo maestro,<p> al pulsar en agregar coco se añadira una cocacola a la maquina,<p> al activar el boton de guardar dinero,<p> cualquier cantidad de dinero ingresada se guardara en la maquina,<p>asegurarse de apagar el boton guardar dinero al cerrar el modo maestro,<p>en caso de que no tenga cocas la maquina se regresara tu cambio,<p>en caso de que no tenga cambio la maquina te pedira ingresar el cambio exacto pero solo regresara <p>el cambio si pulsas el boton cambio<html>","Funcionamiento",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public Icon setIcono(String a,JButton b){
        ImageIcon icon = new ImageIcon(getClass().getResource(a));
        int ancho=b.getWidth();
        int alto=b.getHeight();
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        return icono;
    }
    
    public Icon setPressIcon(String a,JButton b,int ancho,int altura){
        ImageIcon icon = new ImageIcon(getClass().getResource(a));
        int anc = b.getWidth() - ancho;
        int alt = b.getHeight() - altura;
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(anc, alt, Image.SCALE_DEFAULT));
        return icono;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maquina().setVisible(true);
            }
        });
    }


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddcc;
    private javax.swing.JButton btnCambio;
    private javax.swing.JToggleButton btnGd;
    private javax.swing.JButton btnM1;
    private javax.swing.JButton btnM2;
    private javax.swing.JButton btnM3;
    private javax.swing.JButton btnM4;
    private javax.swing.JButton btnM5;
    private javax.swing.JButton btnM6;
    private javax.swing.JButton btnM7;
    private javax.swing.JButton btnM8;
    private javax.swing.JToggleButton btnMaster;
    private custom.customPanel customPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblC100p;
    private javax.swing.JLabel lblC10p;
    private javax.swing.JLabel lblC1p;
    private javax.swing.JLabel lblC200p;
    private javax.swing.JLabel lblC20p;
    private javax.swing.JLabel lblC2p;
    private javax.swing.JLabel lblC500p;
    private javax.swing.JLabel lblC50p;
    private javax.swing.JLabel lblC5p;
    private javax.swing.JLabel lblCcc;
    private javax.swing.JLabel lblPnl;
    private javax.swing.JButton p1;
    private javax.swing.JButton p10;
    private javax.swing.JButton p100;
    private javax.swing.JButton p2;
    private javax.swing.JButton p20;
    private javax.swing.JButton p200;
    private javax.swing.JButton p5;
    private javax.swing.JButton p50;
    private javax.swing.JButton p500;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
       
            Integer precio=17;
            if(credito<precio){
                lblPnl.setText("<html>Bienvenido usuario <p>Porvafor elija su producto<p>Precio del producto:$17<html>");
            }else if(cc==0){
                regresarCambiosinCC();
            }else if(evaluarCambio()){
                lblPnl.setText("<html>Porfavor Ingrese cambio exacto<html>");
            }else{
                regresarCambio();
            }
    }
    public void regresarCambio(){
        Integer i=500;
        Integer r=0;
        Integer a=credito-17;
        Integer cuenta=0;
        while(i>0&&a!=0){
            Integer b=a-i;
            if((b>=0)&&(evaluarexistencia(i))){
            r++;
            agregarcuenta(i);
            cuenta+=i;
            a=b;
            }else{
            i=evaluari(i);
            r=0;
            }
            System.out.println(a+"/"+b+"/"+i+"/"+cuenta+"/"+r);
        }
        imprimircambio();
        cc--;
        lblCcc.setText(cc+" Botellas de coca");
        credito=0;
        lblPnl.setText("<html>Bienvenido usuario <p>Porvafor elija su producto<p>");
        resetcambio();
        actualizarfondos();
    }
    
    public void imprimircambiosincc(){
        String resultado="Lo sentimos, no nos quedan cocas. Tu cambio es de: ";
        if(c1>0){
            resultado=resultado+c1+" monedas de 1 peso";
        }
        if(c2>0){
            resultado=resultado+c2+" monedas de 2 pesos";
        }
        if(c5>0){
            resultado=resultado+c5+" monedas de 5 pesos";
        }
        if(c10>0){
            resultado=resultado+c10+" monedas de 10 pesos";
        }
        if(c20>0){
            resultado=resultado+c20+" billetes de 20 pesos";
        }
        if(c50>0){
            resultado=resultado+c50+" billetes de 50 pesos";
        }
        if(c100>0){
            resultado=resultado+c100+" billetes de 100 pesos";
        }
        if(c200>0){
            resultado=resultado+c200+" billetes de 200 pesos";
        }
        if(c500>0){
            resultado=resultado+c500+" billetes de 500 pesos";
        }
        JOptionPane.showMessageDialog(this, resultado, "Cambio",JOptionPane.INFORMATION_MESSAGE);
        lblCcc.setText(cc+" Botellas de coca");
        credito=0;
        lblPnl.setText("<html>Bienvenido usuario <p>Porvafor elija su producto<p>");
    }
    
    public void imprimircambio(){
        String resultado="Tu cambio es de: ";
        if(c1>0){
            resultado=resultado+c1+" monedas de 1 peso";
        }
        if(c2>0){
            resultado=resultado+c2+" monedas de 2 pesos";
        }
        if(c5>0){
            resultado=resultado+c5+" monedas de 5 pesos";
        }
        if(c10>0){
            resultado=resultado+c10+" monedas de 10 pesos";
        }
        if(c20>0){
            resultado=resultado+c20+" billetes de 20 pesos";
        }
        if(c50>0){
            resultado=resultado+c50+" billetes de 50 pesos";
        }
        if(c100>0){
            resultado=resultado+c100+" billetes de 100 pesos";
        }
        if(c200>0){
            resultado=resultado+c200+" billetes de 200 pesos";
        }
        if(c500>0){
            resultado=resultado+c500+" billetes de 500 pesos";
        }
        JOptionPane.showMessageDialog(this, resultado, "Cambio",JOptionPane.INFORMATION_MESSAGE);
        lblCcc.setText(cc+" Botellas de coca");
        credito=0;
        lblPnl.setText("<html>Bienvenido usuario <p>Porvafor elija su producto<p>");
    }
    
    public void agregarcuenta(Integer i){
        switch(i){
            case 1:
                c1++;
                System.out.println("quite"+i);
                m1--;
                break;
            case 2:
                System.out.println("quite"+i);
                c2++;
                m2--;
                break;
            case 5:
                System.out.println("quite"+i);
                c5++;
                m5--;
                break;
            case 10:
                System.out.println("quite"+i);
                c10++;
                m10--;
                break;
            case 20:
                System.out.println("quite"+i);
                c20++;
                b20--;
                break;
            case 50:
                System.out.println("quite"+i);
                c50++;
                b50--;
                break;
            case 100:
                System.out.println("quite"+i);
                c100++;
                b100--;
                break;
            case 200:
                System.out.println("quite"+i);
                c200++;
                b200--;
                break;
            case 500:
                System.out.println("quite"+i);
                c500++;
                b500--;
                break;
        }
    }
    
    public void regresarCambiosinCC(){
        Integer i=500;
        Integer a=credito;
        Integer cuenta=0;
        Integer r=0;
        while(i>0&&a!=0){
            Integer b=a-i;
            if(b>=0&&evaluarexistencia(i)){
            r++;
            agregarcuenta(i);
            a=b;
            }else{
                r=0;
                i=evaluari(i);
            }
            System.out.println(a+"/"+b+"/"+i+"/"+cuenta+"/"+r);
        }
        imprimircambiosincc();
        actualizarfondos();
        lblCcc.setText(cc+" Botellas de coca");
        credito=0;
        lblPnl.setText("<html>Bienvenido usuario <p>Porvafor elija su producto<p>");
        resetcambio();
    }
    
    public void actualizarfondos(){
        lblC1p.setText(m1+" Monedas de 1 peso");
        lblC2p.setText(m2+" Monedas de 2 pesos");
        lblC5p.setText(m5+" Monedas de 5 pesos");
        lblC10p.setText(m10+" Monedas de 10 pesos");
        lblC20p.setText(b20+" Billetes de 20 pesos");
        lblC50p.setText(b50+" Billetes de 50 pesos");
        lblC100p.setText(b100+" Billetes de 100 pesos");
        lblC200p.setText(b200+" Billetes de 200 pesos");
        lblC500p.setText(b500+" Billetes de 500 pesos");  
    }
    
    public void resetcambio(){
        c1=0;
        c2=0;
        c5=0;
        c10=0;
        c20=0;
        c50=0;
        c100=0;
        c200=0;
        c500=0;
    }
    
    public boolean evaluarCambio(){
        Integer i=500;
        Integer r=0;
        System.out.println(credito);
        Integer a=credito-17;
        System.out.println(credito);
        Integer cuenta=0;
        while(i>0&&a!=0){
            Integer b=a-i;
            if(b>=0&&evaluarexistencia(i,r)){
            cuenta+=i;
            a=b;
            }else{
            i=evaluari(i);
            r=0;
            }
            System.out.println(a+"/"+b+"/"+i+"/"+cuenta);
            
        }
        System.out.println("///////////");
        if(cuenta!=(credito-17)){
            return true;
        }
        return false;
    
    }
    public Integer evaluari(Integer i){
        switch(i){
            case 1:
                i=0;
                break;
            case 2:
                i=1;
                break;
            case 5:
                i=2;
                break;
            case 10:
                i=5;
                break;
            case 20:
                i=10;
                break;
            case 50:
                i=20;
                break;
            case 100:
                i=50;
                break;
            case 200:
                i=100;
                break;
            case 500:
                i=200;
                break;
        }
    return i;
    }
    public boolean evaluarexistencia(Integer i){
        Integer r=0;
        Integer a;
        switch(i){
            case 1:
                a=m1-r;
                if(a<=0){
                return false;
                }
                break;
            case 2:
                a=m2-r;
                if(a<=0){
                return false;
                }
                break;
            case 5:
                a=m5-r;
                if(a<=0){
                return false;
                }
                break;
            case 10:
                a=m10-r;
                System.out.println("//"+m10+r+a);
                if(a<=0){
                return false;
                }
                break;
            case 20:
                a=b20-r;
                if(a<=0){
                return false;
                }
                break;
            case 50:
                 a=b50-r;
                if(a<=0){
                return false;
                }
                break;
            case 100:
                 a=b100-r;
                if(a<=0){
                return false;
                }
                break;
            case 200:
                 a=b200-r;
                if(a<=0){
                return false;
                }
                break;
            case 500:
                 a=b500-r;
                if(a<=0){
                return false;
                }
                break;
        }
        return true;
    }
    public boolean evaluarexistencia(Integer i,Integer r){
        Integer a=0;
        switch(i){
            case 1:
                a=m1-r;
                if(a<=0){
                return false;
                }
                break;
            case 2:
                a=m2-r;
                if(a<=0){
                return false;
                }
                break;
            case 5:
                a=m5-r;
                if(a<=0){
                return false;
                }
                break;
            case 10:
                a=m10-r;
                System.out.println("//"+m10+r+a);
                if(a<=0){
                return false;
                }
                break;
            case 20:
                a=b20-r;
                if(a<=0){
                return false;
                }
                break;
            case 50:
                 a=b50-r;
                if(a<=0){
                return false;
                }
                break;
            case 100:
                 a=b100-r;
                if(a<=0){
                return false;
                }
                break;
            case 200:
                 a=b200-r;
                if(a<=0){
                return false;
                }
                break;
            case 500:
                 a=b500-r;
                if(a<=0){
                return false;
                }
                break;
        }
        return true;
    }
}
